version: '3.5'

services:
  kafka-connect:
    deploy:
      placement:
        constraints:
          - node.hostname == ${PLACEMENT_CONSTRAINTS_NODE_HOSTNAME:-hostname}

volumes:
  jars-vol:
    name: ${CONNECT_JARS_VOL_NAME:-connect-jars-vol}
